version: '3'
services:
  mongo:
    image: mongo:5.0.16
    volumes:
      - db_data:/data/db
    ports:
      - ${DOCKER_MONGO_PORT}:27017
    networks:
      - bridge

  redis:
    image: bitnami/redis:6.0
    ports:
      - "26379:6379"
    volumes:
      - db_data:/var/lib/redis
      - db_data:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - bridge

  award-api:
    build: .
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - /var/log/award-api:/usr/src/app/logs
    depends_on:
      - mongo
      - redis
    environment:
      DATABASE_URL: mongodb://mongo:27017
      DATABASE_NAME: ${DATABASE_NAME}
      REDIS_URL: redis://redis
    networks:
      - bridge

networks:
  bridge:


volumes:
  db_data:
